const UPDATE_LOCATION_INTERVAL = 15;
const UPDATE_LIST_INTERVAL = 15;
//humans walk at a speed of avg 1.2m/s. so 2,5 is good gues
const THRESHOLD_SPEED_TO_BE_CALLED_MOVING = 0;
const NUMBER_OF_GROPUED_POINTS_TO_BE_CALLED_BUS = 10;
const NOTIFICATION_ID = 1989;
